### ISSUE TITLE
Syntax highlighting convention

### ISSUE THREAD

**Issue by raldridge11** [raldridge11/FortranVS#2]
Conventions for syntax highlighting needs to be decided upon.

**Comment by rjgtorres** [comment]
Since I'm here let me comment on this. If you look at the repository I sent you in the other issue you can see that I've colored the % and comma (,) symbols. Now that I'm used to it I find really difficult to read code without those colors. The % lets you easily check data structures, classes and methods. The (,) is specially useful to differentiate input arguments in functions and dimensions in arrays bigger than 2.

**Comment by raldridge11** [comment]
In VS 2015 Update 1+, support for Textmate grammars has been [added](https://docs.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages). A Textmate grammar for [Fortran](https://github.com/textmate/fortran.tmbundle) has already been created. To not duplicate work, FortranVS will use the Textmate grammar files for Fortran.
